export const ENDPOINTS = Object.freeze({
  auth: {
    login: "/auth/login",
    logout: "/auth/logout",
    refresh: "/auth/refresh",
    me: "/auth/me",
    registerUser: "/auth/register-user",
    changePassword: "/auth/change-password",
  },
  users: {
    base: "/users",
    byId: (id) => `/users/${id}`,
  },
  admins: {
    base: "/admins",
    byId: (id) => `/admins/${id}`,
    permissions: (id) => `/admins/${id}/permissions`,
    password: (id) => `/admins/${id}/password`,
    catalog: "/admins/permission-catalog",
  },
  activityLogs: {
    base: "/activity-logs",
    byId: (id) => `/activity-logs/${id}`,
    stats: "/activity-logs/stats",
  },
  cars: {
    base: "/cars",
    byId: (id) => `/cars/${id}`,
    expiring: "/cars/expiring",
    documents: (id) => `/cars/${id}/documents`,
    documentById: (id, docId) => `/cars/${id}/documents/${docId}`,
  },
  carDocumentTypes: {
    base: "/car-document-types",
    byId: (id) => `/car-document-types/${id}`,
  },
  drivers: {
    base: "/drivers",
    byId: (id) => `/drivers/${id}`,
    balance: (id) => `/drivers/${id}/balance`,
    endTrial: (id) => `/drivers/${id}/end-trial`,
    changeTariff: (id) => `/drivers/${id}/change-tariff`,
    deposit: (id) => `/drivers/${id}/deposit`,
    warnings: "/drivers/warnings",
    documents: (id) => `/drivers/${id}/documents`,
    documentById: (id, docId) => `/drivers/${id}/documents/${docId}`,
  },
  driverDocumentTypes: {
    base: "/driver-document-types",
    byId: (id) => `/driver-document-types/${id}`,
  },
  restDays: {
    base: "/rest-days",
    byId: (id) => `/rest-days/${id}`,
    calendar: "/rest-days/calendar",
  },
  payments: {
    base: "/payments",
    byId: (id) => `/payments/${id}`,
  },
  fines: {
    base: "/fines",
    byId: (id) => `/fines/${id}`,
  },
  damages: {
    base: "/damages",
    byId: (id) => `/damages/${id}`,
  },
  oyliklar: {
    base: "/oyliklar",
    byId: (id) => `/oyliklar/${id}`,
    currentForDriver: (driverId) => `/oyliklar/driver/${driverId}/current`,
    statementForDriver: (driverId) => `/oyliklar/driver/${driverId}/statement`,
    payouts: (id) => `/oyliklar/${id}/payouts`,
    payoutById: (id, payoutId) => `/oyliklar/${id}/payouts/${payoutId}`,
  },
  reports: {
    dailyPlanTotal: "/reports/daily-plan-total",
    finance: "/reports/finance",
    minYear: "/reports/min-year",
    monthlyIncomeExpense: "/reports/monthly-income-expense",
    depositDriversMonthly: "/reports/deposit-drivers-monthly",
    dailyIncomeExpense: "/reports/daily-income-expense",
    categoryMonthly: "/reports/category-monthly",
  },
  finePayments: {
    base: "/fine-payments",
    byId: (id) => `/fine-payments/${id}`,
    byFine: (fineId) => `/fine-payments/by-fine/${fineId}`,
  },
  damagePayments: {
    base: "/damage-payments",
    byId: (id) => `/damage-payments/${id}`,
    byDamage: (damageId) => `/damage-payments/by-damage/${damageId}`,
  },
  transactions: {
    base: "/transactions",
    byId: (id) => `/transactions/${id}`,
    summary: "/transactions/summary",
  },
  transactionCategories: {
    base: "/transaction-categories",
    byId: (id) => `/transaction-categories/${id}`,
  },
});
